
/**
 * DAK Reporting data model
 *
 * This file defines the structure of one report.
 * It does not contain UI, SQLite, Excel or PDF logic.
 */

/**
 * A report can be saved as a draft or marked completed.
 */
export type ReportStatus = "draft" | "completed";

/**
 * JSON-compatible data types.
 *
 * These allow report answers to be serialized into JSON
 * and stored in SQLite.
 */
export type JsonPrimitive = string | number | boolean | null;

export type JsonValue =
  | JsonPrimitive
  | JsonValue[]
  | { [key: string]: JsonValue };

/**
 * Reusable metadata for a report.
 */
export interface ReportMetadata {
  /** Unique ID for this report. */
  id: string;

  /** Selected reporting month in YYYY-MM format. */
  reportingMonth: string;

  /** Reporting period, e.g. 26/08/2026-25/09/2026. */
  reportingPeriod: string;

  /** District name. */
  district: string;

  /** Block/prakhand name. */
  block: string;

  /** DAK coordinator name. */
  coordinatorName: string;
}

/**
 * One repeated meeting entry.
 *
 * Optional properties should only be populated if the
 * corresponding fields exist in the Excel template.
 */
export type MeetingEntry = {
  panchayat: string;
  date: string;
  meetingNumber?: number;
  attendance?: number;
};

/**
 * One safety audit entry.
 */
export type SafetyAuditEntry = {
  panchayat: string;
  date: string;
  issues?: string;
};

/**
 * All answers that belong to a report.
 *
 * Examples:
 * - Counts and Yes/No answers
 * - Free-text descriptions
 * - Selected roles
 * - Repeated meetings and audits
 *
 * Keys are stable field IDs, not Excel column letters.
 */
export interface ReportValues {
  /**
   * Meeting chairperson roles.
   * Example: ["Leader", "CC", "BPM"]
   */
  meetingChairperson?: string[];

  /**
   * Multiple PLGF meeting entries.
   */
  plgfMeetings?: MeetingEntry[];

  /**
   * Multiple safety audit entries.
   */
  safetyAudits?: SafetyAuditEntry[];

  /**
   * Multiple adolescent-group meeting entries.
   */
  adolescentGroupMeetings?: MeetingEntry[];

  /**
   * Other answers, using stable field IDs.
   *
   * Examples:
   * "domestic_violence_cases": 5
   * "helpline_available": "Yes"
   * "safety_audit_issues": "Long description..."
   */
  [fieldId: string]: unknown;
}

/**
 * Complete report stored by the application.
 */
export interface DakReport extends ReportMetadata {
  /** All form answers. */
  values: ReportValues;

  /** Current report status. */
  status: ReportStatus;

  /** ISO timestamp when the report was created. */
  createdAt: string;

  /** ISO timestamp of the most recent save. */
  updatedAt: string;
}

/**
 * Input required to create a new report.
 *
 * The ID and timestamps are generated by the application.
 */
export interface CreateDraftReportInput {
  reportingMonth: string;
  reportingPeriod: string;
  district: string;
  block: string;
  coordinatorName: string;
}

/**
 * Creates a new, empty draft report.
 *
 * Pass a unique ID generated by the application.
 */
export function createDraftReport(
  input: CreateDraftReportInput,
  id: string
): DakReport {
  const now = new Date().toISOString();

  return {
    id,
    reportingMonth: input.reportingMonth,
    reportingPeriod: input.reportingPeriod,
    district: input.district.trim(),
    block: input.block.trim(),
    coordinatorName: input.coordinatorName.trim(),
    values: {},
    status: "draft",
    createdAt: now,
    updatedAt: now,
  };
}

/**
 * Updates a report without modifying the original object.
 */
export function updateDraftReport(
  report: DakReport,
  changes: Partial<
    Pick<
      DakReport,
      | "reportingMonth"
      | "reportingPeriod"
      | "district"
      | "block"
      | "coordinatorName"
      | "values"
      | "status"
    >
  >
): DakReport {
  return {
    ...report,
    ...changes,
    updatedAt: new Date().toISOString(),
  };
}

/**
 * Marks a report as completed.
 *
 * Required-field validation will be implemented separately
 * before this function is called.
 */
export function completeReport(report: DakReport): DakReport {
  return {
    ...report,
    status: "completed",
    updatedAt: new Date().toISOString(),
  };
}

/**
 * Converts a report into a JSON string for SQLite storage.
 */
export function serializeReport(report: DakReport): string {
  return JSON.stringify(report);
}

/**
 * Restores a report from its JSON string.
 *
 * This checks the basic structure. More detailed validation
 * can be added when loading records from SQLite.
 */
export function deserializeReport(json: string): DakReport {
  const parsed: unknown = JSON.parse(json);

  if (
    typeof parsed !== "object" ||
    parsed === null ||
    !("id" in parsed) ||
    !("reportingMonth" in parsed) ||
    !("reportingPeriod" in parsed) ||
    !("district" in parsed) ||
    !("block" in parsed) ||
    !("coordinatorName" in parsed) ||
    !("values" in parsed) ||
    !("status" in parsed) ||
    !("createdAt" in parsed) ||
    !("updatedAt" in parsed)
  ) {
    throw new Error("Invalid DAK report data.");
  }

  const report = parsed as DakReport;

  if (
    typeof report.id !== "string" ||
    typeof report.reportingMonth !== "string" ||
    typeof report.reportingPeriod !== "string" ||
    typeof report.district !== "string" ||
    typeof report.block !== "string" ||
    typeof report.coordinatorName !== "string" ||
    typeof report.values !== "object" ||
    report.values === null ||
    Array.isArray(report.values) ||
    !["draft", "completed"].includes(report.status) ||
    typeof report.createdAt !== "string" ||
    typeof report.updatedAt !== "string"
  ) {
    throw new Error("Invalid DAK report fields.");
  }

  return report;
}
